[package]
name = "repology-updater"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
repology-common = { path = "../repology-common" }
anyhow = "1.0.98"
strum = { version = "0.27.1", features = ["derive"] }
bitflags = "2.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
walkdir = "2.5.0"
toml = { version = "0.9.0", default-features = false, features = ["serde", "parse"] }

[dev-dependencies]
insta = "1.43.1"
tempfile = "3.20.0"
