[package]
name = "repology-updater"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
strum = { version = "0.27.1", features = ["derive"] }

[lints]
workspace = true

[dev-dependencies]
tempfile = "3.20.0"
