# For module hosting facilities (rubygems, pypi, cpan) we set larger recheck time
# since there are a lot of links, but the links are unlikely to change status
# This list is |sort friendly, please keep sorted
"abf.io".generated_sampling_percentage = 10
"abf.io".recheck_generated = 21
"aur.archlinux.org".recheck_generated = 45
"bugs.freebsd.org".delay = 30               # 429s @ 3sec
"build.debian.org".delay = 60               # sensitive to load
"build.debian.org".recheck_generated = 400  # because of huge delay
"build.opensuse.org".generated_sampling_percentage = 10
"build.opensuse.org".recheck_generated = 21
"codeberg.org".delay = 30                   # 429s @ 30sec
"community.chocolatey.org".disable_head = true
"cpan.metacpan.org".recheck_manual = 14
"crates.io".recheck_generated = 60
"crates.io".recheck_manual = 60
"crates.io".skip = true                     # misconfigured crap, always 404; XXX = this is true only for crate pages, not for e.g. https://crates.io/api/v1/crates/abscissa_core/0.5.2/download
"dev.exherbo.org".recheck_generated = 30    # broken, 60+ sec checks
"dev.exherbo.org".recheck_manual = 30       # broken, 60+ sec checks
"dev.exherbo.org".timeout = 5               # broken, 60+ sec checks
"dev.gentoo.org".delay = 1
"files.pythonhosted.org".delay = 1
"files.pythonhosted.org".generated_sampling_percentage = 1  # no real need to recheck links provided by pypi itself, right?
"files.pythonhosted.org".recheck_generated = 30
"files.pythonhosted.org".recheck_manual = 30
"gitee.com".delay = 5                       # 429s @ 3sec
"gitee.com".generated_sampling_percentage = 10
"github.com".delay = 2
"github.com".generated_sampling_percentage = 10
"github.com".recheck_generated = 45
"github.com".recheck_manual = 21
"github.io".is = "github.com"
"githubusercontent.com".is = "github.com"
"gitlab.com".delay = 1
"hydra.nixos.org".generated_sampling_percentage = 1
"kojipkgs.fedoraproject.org".generated_sampling_percentage = 10
"madoguchi.fyralabs.com".delay = 5          # 429s @ 3 sec
"marketplace.visualstudio.com".disable_head = true
"mran.revolutionanalytics.com".recheck_manual = 14
"notabug.org".delay = 60
"npmjs.com".delay = 10
"npmjs.org".delay = 10
"packman.links2linux.org".disable_head = true
"pkgs.alpinelinux.org".recheck_generated = 45
"pypi.org".delay = 1                        # lots of links, claims (XXX: source?) to handle much trafic
"pypi.org".recheck_manual = 14
"readthedocs.io".aggregate = true
"rubygems.org".delay = 1
"rubygems.org".recheck_manual = 14
"search.cpan.org".recheck_manual = 14
"sf.net".is = "sourceforge.net"
"sourceforge.io".is = "sourceforge.net"
"sourceforge.net".aggregate = true
"src.fedoraproject.org".generated_sampling_percentage = 1
"static.crates.io".skip = false             # exclude this host from crates.io skip rule above

# Blacklist (domain for sale, overtaken, spam etc.)
# This list is |sort friendly, please keep sorted
"antigrain.com".blacklist = true
"aseman.co".blacklist = true
"astroid.org".blacklist = true
"beryl-project.org".blacklist = true
"boutell.co.uk".blacklist = true
"conduit-project.org".blacklist = true
"coolreader.org".blacklist = true
"cross-pcg.com".blacklist = true
"dejavu-fonts.org".blacklist = true
"ekg2.org".blacklist = true
"ferite.org".blacklist = true
"glimpse-editor.org".blacklist = true
"gnugadu.org".blacklist = true
"htdig.org".blacklist = true
"htpc-forum.de".blacklist = true
"jnickelsen.de".blacklist = true
"junoplay.com".blacklist = true
"kermit-project.org".blacklist = true
"kmldonkey.org".blacklist = true
"konst.org.ua".blacklist = true
"libcapn.org".blacklist = true
"mandriva.com".blacklist = true
"mepis.org".blacklist = true
"nimuh.com".blacklist = true
"ofset.org".blacklist = true
"opensync.org".blacklist = true
"opentnl.org".blacklist = true
"qtoctave.wordpress.com".blacklist = true
"somethingaboutorange.com".blacklist = true
"svn.mandriva.com".blacklist = true
"thekonst.net".blacklist = true
"tkzinc.org".blacklist = true
"topfx.com".blacklist = true
"wmii.de".blacklist = true
"yafray.org".blacklist = true
