version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Topic: dependencies"
      - "Priority: soon"
    commit-message:
      prefix: cargo
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Topic: dependencies"
      - "Priority: soon"
    commit-message:
      prefix: ci
