[workspace]
members = ["repology-common", "repology-webapp", "libversion", "repology-webapp-test-utils", "repology-vulnupdater"]
resolver = "3"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
