[package]
name = "repology-vulnupdater"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
async-compression = { version = "0.4.12", features = ["gzip", "tokio"] }
async-trait = "0.1.83"
chrono = { version = "0.4.38", default-features = false, features = ["now"] }
clap = { version = "4.5.18", features = ["derive"] }
json = "0.12.4"
reqwest = { version = "0.12.7", features = ["stream"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
sqlx = { version = "0.8.2", features = ["postgres", "chrono", "runtime-tokio"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1.16", default-features = false }
tokio-util = { version = "0.7.12", features = ["io"] }
