name: CI
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      matrix:
        include:
          - { name: "Rust stable", rust: stable, cargo_args: "" }
          - { name: "Rust nightly", rust: nightly, cargo_args: "" }
          - { name: "Rust nightly, release", rust: nightly, cargo_args: "--release" }
      fail-fast: false
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            target/
          key: cargo-${{ matrix.rust }}-${{ matrix.cargo_args }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ matrix.rust }}-${{ matrix.cargo_args }}-
            cargo-${{ matrix.rust }}-
      - name: Build
        run: cargo build ${{ matrix.cargo_args }}
        env:
          RUSTFLAGS: -Dwarnings
      - name: Test
        run: cargo test ${{ matrix.cargo_args }}
      - name: Format check
        run: cargo fmt --check
